download.md

Hi there,
just a quick update of the download.md to reflect recent Escape Studios repo changes...
Thanks in advance for merging the update!
Kind regards,
David

Updated download.md - escapestudios repo changes

---

doc/protocol.zh-CN.md

Signed-off-by: Tony Deng <wolf.deng@gmail.com>

style(1.10): 修复beanstalkd中文版协议在github上Markdown标题格式不规范问题

---

CodeOfConduct.txt
Contributing
README

Should have done this long, long ago.

add a code of conduct

---

README.md

Add some formatting  and Travis CI build badge.
Updates  #396

use markdown for the root readme file

---

adm/systemv/beanstalkd.init

Recreating PR since the original author has deleted the branch.
closes #178

add System V init script

---

pkg/dist.sh

Signed-off-by: Thomas Parrott <tomp@tomp.uk>

fix mktemp argument to work on ubuntu 18.04

---

doc/protocol.txt
prot.c

add draining status to the "stats" command

---

ct/ct.c
ct/gen

update ct to kr/ct@d16c7bc

---

README.md

make protocol.txt more visible on github

---

file.c
main.c
prot.c

This is a start in a series of patches to fix
warnings from "cppcheck --enable=all --inconclusive --std=posix ."

improve readability of the code in some places

---

prot.c

Choose better names for these functions to reflect their purpose.
Remove the read_ttr function and use "read_duration" in it's place.
Updates #230

rename functions read_pri to read_num, read_ttr to read_duration

---

doc/protocol.txt

protocol.txt: fix typos

---

dat.h
prot.c
walg.c

This parameter is not used in the function at all.
Updates #443

remove the j parameter from the walresvupdate function

---

testserv.c

test the "deadline_soon" and the connclose function

---

testserv.c

test list-tube* commands

---

dat.h
linux.c
main.c
testserv.c
tube.c

fix struct initializers to fix -Wextra warnings

---

testserv.c

On some machines the release might not happen soon enough
after the connection holding the job was closed. Instead of
adding artifical timeout I have added reserving with timeout of 1 second.
Test will pass if the job is released sooner than in 1 second.
It should be enought even for the most slow machines.
Fixes #475

fix the close_releases_job test

---

.travis.yml
Makefile
conn.c
dat.h
ms.c
prot.c
testms.c
tube.c

I have renamed ms.used to ms.len, added comments explaining
the ms structure. Tests were added, including a little confusing
behaviour of function ms_take. The order of taken elements is
not the same as the order of inserts.

test ms and improve code style of it

---

dat.h

dat.h: fix misleading comment about Walver

---

README.md

README.md: mention C99 as required compiler, Illumos as supported OS

---

doc/protocol.zh-CN.md

Fix wrong translate peek section of chinese protocol document.

Fix #485 Chinese protocol wrong translate of peek section.

---

testheap.c

fix memory leak in the heap benchmarks

---

.codecov.yml
.travis.yml

move ignored coverage files from .travis.yml to .codecov.yml

---

conn.c
dat.h
ms.c
prot.c
testms.c
tube.c

drop the pointer from the ms typedef

---

conn.c
dat.h
file.c
job.c
main.c
prot.c
testheap.c
testjobs.c
testserv.c
tube.c
walg.c

This patch is a hell of a (Job *).
Updates #458

drop the pointer from the job typedef

---

conn.c
dat.h
file.c
job.c
prot.c
testjobs.c
tube.c

drop the pointer from the tube typedef

---

prot.c

For consistency, use `reply_msg` macro instead.

Cleanup message length macros

---

prot.c
tube.c

It is confusing to understand and it is against C99.
Also remove redundant returns in end of of functions.

do not return void expressions

---

doc/protocol.zh-CN.md

1. Chinese doc revised for human reading
2. improving markdown doc format
3. add some  detailed explanation
4. fix some typo

Chinese doc revised for human reading

---

dat.h
file.c
prot.c
serv.c
testserv.c
util.c
walg.c

* remove global vars where possible
* reduce scope of variables
* remove shadowing of variables
* remove redundant assigments
* fix prototypes according to the definion of functions
Updates #442

fix style of the code

---

ms.c

ms.c: simplify the code checking OOM in the grow function

---

.codecov.yml

Ignore sd-daemon.* since we are not going to test it,
ignore "doc/*" and use more sane scale for coloring the badge.
Fixes #500

add merge check with threshold of 0.5%

---

conn.c
dat.h
prot.c
tube.c

No functional changes in this patch.

add more comments and style fixes

---

doc/protocol.zh-CN.md

https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L137-L139
https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L146

add delay ttr maximum value

---

prot.c

Spotted by @Thoro: https://github.com/beanstalkd/beanstalkd/pull/562#issuecomment-614499194

remove accidental debugging printf

---

CHANGELOG.md
doc/beanstalkd.1
doc/beanstalkd.1.html
doc/beanstalkd.ronn

add changelog

---

CHANGELOG.md

Signed-off-by: Thomas Parrott <tomp@tomp.uk>

Updates changelog with 1.12 release

---

testserv.c

Fix test regression

---

.github/workflows/test-clients.yaml

Greenstalk #9 fixed
