beanstalkd/beanstalkd

- Makefile
When installing within [Open Embedded](http://www.openembedded.org/) the make jobs parameter is by default shared between "all" and "install" [as per this doc](http://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#var-PARALLEL_MAKEINST). The beanstalkd Makefile was causing needless parallelization where the beanstalkd binary may be installed before the directory is created.
> Makefile: resolved parallel install issue

- walg.c
hello @kr 
I think it's a good idea to use max to replace w->next in function walread.
```c
void
walread(Wal *w, job list, int min, int max)
{
File *f;
int i, fd;
int err = 0;
for (i = min; i < w->next; i++) {
...
}
}
```
> MOD: w->next change to max in function walread

- doc/protocol.en-US.md
- doc/protocol.txt
Document delay and ttr values returned by stats-job command. Language borrowed from elsewhere in the docs.
> Document stats-job values delay and ttr

- prot.c
The version number was previously being output as a number. In the case of the current version (1.10) this was parsed as 1.1 by several YAML parsers, including Ruby's YAML, JavaScript's js-yaml and Perl 6's YAMLish. In order for the version number to be parsed correctly it needs to be a string since the trailing zeros are significant.
This change shouldn't affect any existing parsers as the ones that got the correct number are parsing all values as strings anyway.
Of course, since this won't be released until a later version, it won't help. At least not until 1.20 or 2.10.
> Fix version number output in stats

- prot.c
This change updates pause-tube to return BAD_FORMAT when an invalid tube name is supplied. At present pause-tube will return NOT_FOUND after it fails to find an invalid tube.
This is more of a consistency thing than a bug, per se. 
ct tests all pass.
> pause-tube should check tube name is ok

- Makefile
Support originally added in 0f97427a38cd0c2c2aee00946ebe561453165a50.
I'm sure this was left in accidentally as it resets the variable to ''.
> Makefile: finish DESTDIR support

- dat.h
- doc/protocol.en-US.md
- doc/protocol.txt
This fix addresses https://github.com/kr/beanstalkd/issues/211 and https://github.com/kr/beanstalkd/issues/212. 
I tried the approach I suggested in the issue of changing prot.c:343 to use ```>``` instead of ```>=```, but trying to use a tube with a name of length 200 continued having issues. Also given the number of other commands having length issues, this approach would not have solved the larger problem.
So this instead updates LINE_BUF_SIZE to handle the longest possible command and reply lines.
This may be a preferable approach since both LINE_BUF_SIZE and MAX_TUBE_NAME_LEN follow similar logic in that they both represent the minimum invalid length.
Existing ct tests all pass. Additionally a suite of ~200 integration tests I wrote to test adherence to the beanstalk protocol show no …
> Increase LINE_BUF_SIZE to handle longest possible command

- doc/protocol.txt
> Document "drain mode"

- download.md
I stumbled across #215 and it just felt like it would be more natural to have on the [Tools page](https://github.com/kr/beanstalkd/wiki/Tools). I've updated the wiki page to include the puppet and chef stuff. This pull request simply refers users there.
> Use wiki for deployment/automated installation tools

- net.c
When binding to port 0 beanstalk correctly binds to a random port but doesn't report which port it bound to, reporting 0 instead. This patch fixes that.
> Report bound port correctly

- linux.c
Embedded systems (such as OpenWRT) often have reduced functionality; when operating in such circumstances, using the most widely available API's (or subsets of API's) is key for portability.  ftruncate() is much more ubiquitous than posix_fallocate().
> Use ftruncate() as it's much more portable

- README
- doc/beanstalkd.1
- doc/beanstalkd.1.html
- doc/beanstalkd.ronn
- pkg/README.md
- pkg/Readme
- pkg/bloghead.in
- pkg/dist.sh
- pkg/newstail.in
Since gh-page was moved into separate repository,
make the proccess of releasing semi-manual for website.
Fix links to the new site everywhere.
> fix release script to allow releases

- .gitignore
- .travis.yml
- Makefile
I have no idea how to enable code coverage on OSX. Looks like we'll need `brew install lcov` or something like that:
```
clang  -lgcov --coverage  -o beanstalkd darwin.o conn.o file.o heap.o job.o ms.o net.o primes.o prot.o sd-daemon.o serv.o time.o tube.o util.o vers.o walg.o main.o 
ld: library not found for -lgcov
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [beanstalkd] Error 1
```
Another weird thing when use Clang on Linux:
```
./vers.gcno:version '402*', prefer '408*'
./vers.gcno:no functions found
./ct.gcno:version '402*', prefer '408*'
gcov: out of memory allocating 14955062000 bytes after a total of 135168 bytes
./_ctcheck.gcno:version '402*', prefer '408*'
./_ctcheck.gcno:no functions found
./file.gcno:version '402*', prefer '408*' …
```
> Enable code coverage on Travis CI

- LICENSE
- README.md
Add coverage badge and move license and copyright to the LICENSE file.
Updates #396
> add coverage badge and move license information

- Makefile
In the OpenWRT, builds are often done under one system (like x86
Ubuntu) for an ARM image of OpenWRT.  CFLAGS, GCC, LDFLAGS, LD,
DESTDIR, PREFIX, etc. all need to be supplied for the target
system.
Addresses issue #339.
> Have a more cross-compilation friendly Makefile

- adm/systemv/beanstalkd.init
Use -n shorthand for non-empty string tests.
Use if shorthand with && for trivial cases.
Remove unnecessary curlies.
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>
> Cleanup SysV initd script

- .travis.yml
Remove files and directories from coverage report matching exclude patterns:
- `ct/*`
- `adm/*`
- `pkg/*`
- `testheap.c`
- `testjobs.c`
- `testserv.c`
- `testutil.c`
I have no idea why, but ignoring via `codecov.yml` does not work.
Refs: #424
> Improved code coverage report

- testheap.c
- testjobs.c
- testserv.c
- testutil.c
All tests functions are more readble since
word are separated with underscores.
Redundant newlines are removed.
Fixes #441
> fix tests names for more readable ones

- dat.h
- file.c
- prot.c
There is lot of work to be done to satisfy -Wextra.
This is the first step where I have eliminated all
errors related to the non-strict type coercion.
Reduced the scope of some variables.
While at it I have eliminated function "one_cmd" as making
code more complex that it has to be.
> fix types to satisfy -Wextra

- dat.h
- doc/protocol.txt
- job.c
- prot.c
- testserv.c
Before this fix if the value specified in
pri/delay/ttr parameters would equal to 2**32
then it would be messed up and set to zero because of overflow.
And in general, the behaviour was not defined strictly
because the uint type can take different width.
I have fixed the read_num function to parse integer
that fits into range 0 .. 2**32-1. Internally it parses
integer into uint64, but it checks if it fits into uint32.
So it will return success only in this case.
I have added multiple tests checking that behaviour.
Fixes #230
> set input width of pri, delay and ttr params to uint32

- .travis.yml
This prevented codecov from showing correct coverage diff because
the base (master) was not ever built after the merge.
> build master on travis-ci after each merge

- conn.c
- dat.h
- main.c
- prot.c
- sd-daemon.c
- serv.c
- testserv.c
Parameters marked with the UNUSED_PARAMETERS macros cannot be
removed from functions because their prototypes cannot be changed.
Create the srv struct via designated initializers. Also remove NULL
assigment, because this way struct values are set to 0 anyway.
Also declare vars next to their first usage as usual.
Update #443
> mark unused parameters to satisfy -Wextra

- dat.h
- heap.c
- job.c
- prot.c
- testheap.c
- testserv.c
Previously "int" was used, it may be too small on some architectures.
This change uses "size_t" instead, since index cannot be negative.
In the heapremove function it removes the assignment to the heap_index
field of deleted member.
As usual in affected functions, I have moved  declarations of variables close
to their usage.
Updates #443
> use size_t for indexes in the heap structure

- file.c
This prevented compilation with -O2, -O3 levels on Linux with GCC.
Updates #423
> check the return value of ftruncate for possible error

- .travis.yml
Closes: https://github.com/beanstalkd/beanstalkd/issues/423
----
Just for history:
**gcc**
- gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```
CFLAGS=""
--
ctbench_heap_insert	 2000000	       750 ns/op
ctbench_heap_remove	 1000000	      1317 ns/op
ctbench_make_job	10000000	       256 ns/op
ctbench_put_delete_1k	     100	  39684462 ns/op	   0.03 MB/s
ctbench_put_delete_64k	     100	  38777774 ns/op	   2.12 MB/s
ctbench_put_delete_8	     100	  39606825 ns/op	   0.00 MB/s
ctbench_put_delete_8k	     100	  39572750 ns/op	   0.26 MB/s
```
```
CFLAGS="-march=native -mtune=native -O3"
--
ctbench_heap_insert	10000000	       209 ns/op
ctbench_heap_remove	 3000000	       624 ns/op
ctbench_make_job	10000000	       203 ns/op
ctbench_put_delete_1k	     100	  39587950 ns/op	   0.03 MB/s …
```
> Use optimization flags on benchmark

- testserv.c
Test should spend more time than ttr to get job released back into the queue.
> fix flaky deadline-soon test

- prot.c
- testserv.c
Drain mode was quickly tested as well.
The cttest_peek_bad_format test function is commented
until the issue #464 is fixed.
Updates #424
> test peek* and kick commands

- CONTRIBUTING.md
The Go contributing guide has awesome explanation about commit messages.
Fixes #429
> CONTRIBUTING.md: add a link to guide about good commit messages

- testserv.c
It looks like Linux has some issues with performance or events
handling: even after 0.2s after the deadline has expired, sometimes
the job is not released automatically.
This might be related to poor performance in
throughout benchmarks on Linux: it is 60-100 times slower than macOS.
> fix the deadline_soon test with explicit release of the job

- dat.h
- prot.c
- testserv.c
- testutil.c
- util.c
I have set the maximum allowed limit for the job size to 1024^3 bytes (1GB).
When user tries to specify (-z) the limit for the job size larger than that,
he will get a warning that limit was capped to 1GB.
The program stores body_size in int32 (see struct Jobrec) and verifies that 
parameter in the put command can be parsed and fit into int32. 
I have propagated changes to the type of all involved functions.
Fixes #401
> fix the job size overflowing the int type and set hard limit on it

- conn.c
- darwin.c
- dat.h
- file.c
- heap.c
- job.c
- linux.c
- main.c
- ms.c
- net.c
- prot.c
- serv.c
- testheap.c
- testjobs.c
- testserv.c
- testutil.c
- time.c
- tube.c
- util.c
- walg.c
Before this fix my editor was hinting the `*_t` types as undefined. This was confusing.
I have rearranged dat.h and sd-daemon.h before other headers to verify this.
I have removed redefinitions of *_t types because it was producing redefinitions errors.
> include dependent headers in the dat.h file

- conn.c
- dat.h
- prot.c
Previously in #453 I have changed the type of position in the heap to size_t.
I have removed the call x->rec(x, -1) for the item being removed from the heap.
That patch has broken the meaning of conn->tickpos var, that used to
contain -1 when conn was not in the srv->conns heap. -1 was assigned
only when conn was created. Later when it was just removed from conns,
it was not ever assigned -1 again.
This change fixes how connections are handled in the srv->conns heap.
New var Conn->in_conns is used to track if conn exists in the heap.
Conn->tickpos is size_it and the connrec function has a prototype
matching the heap's Record prototype.
Fixes #472
> fix how connections are handled in the srv->conns heap

- .codecov.yml
We need to configure it first, right now even the slightest drop in coverage
results in the blocked merge. This is not good.
> disable codecov from blocking the merge

- testjobs.c
- testserv.c
The slowness in benchmarks on Linux was due to long wait time
in the select syscall. Setting socket's TCP_NODELAY helped.
Also see
https://stackoverflow.com/questions/39270419/select-on-socket-slow-in-linux
I added proper resettimers inside of benchmarks to skip the overhead.
This helped to improve the time spent in all of testsrv tests too.
Bechmarking is not ideal yet. It might be capped by the client's limitations.
Fixes #430
> fix benchmarks in testsrv.c

- conn.c
- dat.h
- heap.c
- job.c
- serv.c
- testheap.c
- tube.c
This change improves readability of the code.
It brings consistency into functions of the binary heap.
Typedef Less was renamed to less_fn, Record to setpos_fn.
connless and connrec were changed to match to the corresponding typdefs.
The rec member of heap was renamed to "setpos".
The job was updated in the same way.
Fixes #472
> fix prototypes of the Less and Record typedefs

- dat.h
- prot.c
- testserv.c
This change fixes how IDs are parsed in all commands.
They are parsed into uint64 with full spectrum of checks.
I added the read_uint64 function identical to read_uint32 (former read_num).
Also read_uint* functions report values not falling into the range as invalid.
I have renamed definitions *_JOBKICK to *_KICKJOB because it was inverted from
actual command.
Updates #424
Fixes #464
> fix the id parsing in all commands and add tests

- testheap.c
- testms.c
- testserv.c
- testutil.c
Additionally, this patch fixes a bug in the cttest_heap_remove_k test. Leak in the server tests are not fixed and require an additional scrutiny. 
Updates #382
> fix leaks in heap, ms, util tests

- dat.h
- job.c
This fix is trivial and the only place needed adjustment was
initialization of the pointer in allocate_job.
Job is still allocated and freed as one block. Performance has
improved slightly, not sure if this just a statistical variance.
We lack proper benchmarking so I cannot say for sure.
Before:
```
ctbench_heap_insert	 3000000	       545 ns/op
ctbench_heap_remove	 1000000	      1003 ns/op
ctbench_make_job	 5000000	       272 ns/op
ctbench_put_delete_1k	    3000	    351086 ns/op	   3.06 MB/s
ctbench_put_delete_64k	    2000	    617025 ns/op	 128.07 MB/s
ctbench_put_delete_8	    5000	    342281 ns/op	   0.04 MB/s
ctbench_put_delete_8k	    3000	    413185 ns/op          24.00 MB/s
```
After:
```
ctbench_heap_insert	 3000000	       546 ns/op
ctbench_heap_remove	 2000000	      1041 ns/op …
```
> convert body to *char and adjust the job's allocation

- conn.c
- darwin.c
- dat.h
- file.c
- job.c
- linux.c
- main.c
- net.c
- prot.c
- serv.c
- sunos.c
- testserv.c
- time.c
- tube.c
- util.c
- walg.c
twarn* macros and warn* functions names are now consistent.
-err suffix means that the function uses errno to print error message.
no suffix means that the function ignores errno.
Updates #488
> make names of warn* functions and macros consistent

- conn.c
- darwin.c
- dat.h
- file.c
- job.c
- linux.c
- main.c
- net.c
- prot.c
- serv.c
- sunos.c
- testserv.c
- time.c
- tube.c
- util.c
- walg.c
This reverts commit c6157f701ca83ed5d5194a53ec8b72c99aa503a9.
> Revert "make names of warn* functions and macros consistent"

- conn.c
- ms.c
- prot.c
- testserv.c
- tube.c
Discovered by -std=c99 -pedantic
> fix ternary operators to not use GNU extension

- dat.h
This is a bit hacky, but this makes code compile in pedantic mode.
It's the shorted solution to the problem so far.
Fixes #488
> make VA_ARGS contain at least one element in twarn* macros

- doc/protocol.txt
- prot.c
This variable name was a poor choice. And in many places id is being used as local var, shadowing the global var. So instead use this unique name.
> rename global var id into instance_hex

- testheap.c
Allocate jobs on the heap instead of stack since n can grow big.
> fix segfault in ctbench_heap_remove

- conn.c
- dat.h
- prot.c
- testserv.c
The name "dirty" did not reveal the purpose of the variable.
I've renamed it to "epollq".
I have removed connwant() and moved its functionality into introduced
function epollq_add(). This function adds a connection as pending for
polling change. protrmdirty() was renamed to epollq_rmconn().
update_conns() was renamed to epollq_apply().
I added a test checking the "quit" command.
Fixes #524
> refactor the code controlling events for sockets

- main.c
- prot.c
Before this patch: when beanstalkd with PID=1 received SIGTERM
running inside of Docker container, the process never exited.
Docker SIGKILLed the process after 10s timeout.
This change adds an ability to handle such case without timeout.
Server will signal itself SIGKILL when SIGTERM is received.
This allows instant termination. This is part of the crash-only
strategy so crashing this way is okay.
Fixes #527
> handle SIGTERM to allow quick exit under Docker

- conn.c
"Placeholder" jobs used to return info (stats, list tube) have their state set to `Copy`, as well as copied jobs for peek commands. Consistent with https://github.com/beanstalkd/beanstalkd/blob/master/prot.c#L1859
There could also be a potential memory leak if a connection is closed with a pending peek job copy (where `c->out_job->r.id` is set).
Sidenote: should there be another enum constant added to better indicate the state of these fake jobs - rather than `Copy`?
> Free placeholder stats/peek job by checking state in connclose

- file.c
- walg.c
> bracket with error-checking all the calls to close() on files

- linux.c
ftruncate() does not return errno.
> linux.c: fix rawfalloc to return errno on error

- dat.h
- main.c
- serv.c
- testserv.c
This removed duplication of code between the testing and server sites.
Also it enables adding specialized function for forking the server in
tests, namely testing of AF_UNIX in #150.
> factor out the code acquiring the wal dir

- doc/beanstalkd.1
- doc/beanstalkd.1.html
- doc/beanstalkd.ronn
- net.c
- prot.c
- testserv.c
Add the posibility of accepting connections from a local socket (bound to a filesystem path).
To minimize portability issues, socket paths longer than 100 bytes are rejected.  Systemd support has been added too, but not tested as I don't have access to any Fedora or similar.
The behaviour of the new command line switch may be strange, but it has been implemented in a way to avoid script breakage when this option is not used.
The automatic socket file replacement may be a bit surprising too.  However, I found that implementing an automatic removal/cleanup on exit was a bit more intrusive.
Any feedback will be appreciated.
> AF_UNIX support for beanstalkd

- testserv.c
The walsize does not affect benchmarks on MacOS, so it was
set to arbitrary value of ~512k.
> add benchmarks for the fsync option turned on

- dat.h
- prot.c
- testserv.c
I have removed the delay_q_take() function because it had
only one line added compared to delay_q_peek(). That line
was put in place. As a result prottick() became easier to read.
> rename delay_q_peek() to soonest_delayed_job()

- net.c
This issue appears on FreeBSD 8.4 where IPV6_V6ONLY is set to 1 by
default. This patch unsets this flag if host was not specified.
Each OS choses the default value for this flag, but it's better
to override it for the case when listening on all interface is
expected.
Fixes #228
> disable forced binding to IPV6-only stack if "-l" was not set

- dat.h
- prot.c
And do collateral renames to improve clarity.
Add a check for not NULL invariant.
> rename deadline_at to unpause_at

- dat.h
- prot.c
- testserv.c
- tube.c
Tube truncation is checked correctly in this patch.
This should not ever happen because code calling it checks
if the tube name is shorter than 201 chars.
Also some tests and fixes for the magic number 200.
Fixes #224
> fix the way tube is truncated

- conn.c
- dat.h
- file.c
- job.c
- net.c
- prot.c
Bunch of functions renamed here and there.
remote_waiting_conn() does not return anything anymore,
instead it is noop for not waiting connection.
reserve_job() body mostly was moved to conn_reserve_job().
the rest was left in place of the call to it.
> improve clarity for job_list_* operations

- darwin.c
- file.c
- linux.c
- sunos.c
- testserv.c
- util.c
Instead of having Linux implementation that uses ftruncate,
allocate files by writing 4096 bytes blocks.
Fixes #537
> write blocks to allocate files in rawfalloc on every OS

- dat.h
- prot.c
The patch fixes segfault after the "put 0 0 0 3000000000" command.
Fixes #555
> fix overflow error with job size bigger than uint32 width

- dat.h
- doc/protocol.txt
- prot.c
The motivation is to have more detailed stats command so that users can report it when they have some problems.
Make counters as uint64 where possible, and rearrange the code.
> add the OS version and platform to the stats command

- dat.h
- doc/beanstalkd.1
- doc/beanstalkd.1.html
- doc/beanstalkd.ronn
- testutil.c
- util.c
- walg.c
Log compaction should not be switched off.
Fixes #552
> remove the -c and -n flags that control log compaction

- doc/protocol.txt
- prot.c
- testserv.c
Before the patch, if a client sent too long command, server would
respond by BAD_FORMAT, followed by UNKNOWN_COMMAND. This resulted
in desync between client and server.
This patch adds another state STATE_WANT_ENDLINE,
whose purpose is to drop command line until the EOL is found.
Client can send as big command as he want and server will be able
to skip it and return only one error message: BAD_FORMAT.
Some STATE_* constants were renamed to improve readability.
Fixes #337
> fix response for the command that is too long

- doc/protocol.txt
- job.c
- prot.c
- testserv.c
A job can be reserved by an ID in the Ready, Buried or Delayed states.
Reservation made with this command does not differ from reservations
made by "reserve" or "reserve-with-timeout" commands. The new command
does not produce "deadline soon" when there are other jobs about to expire.
Fixes #310
Fixes #222
Fixes #240
> add the "reserve-job" command

- job.c
- prot.c
This is to improve readability of some functions:
is_job_reserved_by_conn, touch_job, and is_valid_tube.
> introduce the bool data type

- dat.h
- serv.c
- testserv.c
- testutil.c
- util.c
This won't result in degradation of speed but minimizes the data loss
on disk in the case of server crash.
Benchmarks to prove:
```
ctbench_put_delete_1024			    5000	    321840 ns/op	   4.83 MB/s
ctbench_put_delete_wal_1024_fsync_000ms	     100	  10783976 ns/op	   0.10 MB/s
ctbench_put_delete_wal_1024_fsync_050ms	    3000	    401186 ns/op	   3.01 MB/s
ctbench_put_delete_wal_1024_fsync_200ms	    3000	    372918 ns/op	   3.04 MB/s
ctbench_put_delete_wal_1024_no_fsync	    3000	    358677 ns/op	   3.05 MB/s
ctbench_put_delete_8192			    5000	    389117 ns/op	  37.42 MB/s
ctbench_put_delete_wal_8192_fsync_000ms	     200	   9642472 ns/op	   1.50 MB/s
ctbench_put_delete_wal_8192_fsync_050ms	    2000	    555952 ns/op	  16.20 MB/s
ctbench_put_delete_wal_8192_fsync_200ms	    2000	    524707 ns/op …
```
> sync to the disk every 50ms as default behaviour

- serv.c
The socket is already listening after a call to make_server_socket.
> server: remove redundant listen

- main.c
In Linux SIGKILL is blocked for the process with pid of 1. Instead of
the process sending itself SIGKILL just exit at once.
Fixes #527
> exit when SIGTERM is received and pid is 1

- prot.c
This prevents invalid yaml value when os might contain colons (`:`) such as:
`Darwin Gilad-MBP 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`
> Make sure to quote os value in stats cmd

- testserv.c
Building beanstalkd on big-endian systems (such as s390x, ppc64 and sparc64) currently [fails on the test phase](https://buildd.debian.org/status/fetch.php?pkg=beanstalkd&arch=s390x&ver=1.12-1&stamp=1600854215&raw=0), indicating an error in `mustforksrv()`.
Digging a bit deeper, it turns out this is a type-casting issue between `size_t` (`unsigned long int`) and `socklen_t` (`unsigned int`): `size_t` is 8 bytes, while `socklen_t` is only 4 and these being big-endian systems, actually casting a `size_t *` pointer as `socklen_t *` will set the 4 most significant bytes, rather the least-significant ones, leading to unexpected results.
To better illustrate this, on s390x this code:
```C
size_t sz = 0;
*(socklen_t *)&sz = 4;
printf("*(socklen_t *)&sz = %d, sz = %ld\n", *(socklen_t *)&sz, sz); …
```
> Test failures on big-endian systems

- conn.c
- dat.h
- prot.c
- tube.c
- Removed duplicated assignment for `conn.fd`
- Reused existed `remove_ready_job` to remove job from ready heap for `process_queue`
- Enhanced `tube_find` to find in specified tube sets and not just the global tubes, use it in `OP_IGNORE` handler.
> Optimize small details to make code cleaner

- prot.c
> use read_u32 to safely read reserve-with-timeout argument

- Dockerfile
Support a different base image via build args.
Fixes #603 
Allows users who prefer to self-build to use their own base image with our dockerfile:
`docker build . --build-arg BASE=ubuntu:latest`
Will build beanstalkd then put it into the specified base image!
> Support different base image

- prot.c
Applies the fix from #592  to other string keys.
Fixes #610
> Quote string values in yaml dictionaries

- .github/workflows/test-clients.yaml
This sets up a github action that:
- Builds beanstalkd on any push
- Runs the Pheanstalk test suite against the daemon
It's easily extensible to include other clients.
The idea behind this is that any push or PR confirms that clients won't break (or allows us to identify which clients break and thus give us an early warning for required downstream changes / fixes)
> Build beanstalkd and run PHP Pheanstalk and Python Greenstalk testsuites against it 

- .github/workflows/test-clients.yaml
Fixes #637, the tests for pheanstalk now run and pass.
Adds PyStalk client tests.
Greenstalk still fails so I've disabled it for now.
> Add pystalk client

- main.c
This is a signal handler, so it should accept a signal number as the only argument, otherwise GCC 15 fails with the following error:
```
main.c: In function 'set_sig_handlers':
main.c:75:23: error: assignment to '__sighandler_t' {aka 'void (*)(int)'} from incompatible pointer type 'void (*)(void)' [-Wincompatible-pointer-types]
75 |         sa.sa_handler = handle_sigterm_pid1;
|                       ^
main.c:40:1: note: 'handle_sigterm_pid1' declared here
40 | handle_sigterm_pid1()
| ^~~~~~~~~~~~~~~~~~~
In file included from main.c:3:
/usr/include/signal.h:72:16: note: '__sighandler_t' declared here
72 | typedef void (*__sighandler_t) (int);
|                ^~~~~~~~~~~~~~
```
See also https://bugs.debian.org/1096364.
> Fix handle_sigterm_pid1() signature
